### ISSUE TITLE
Remove "Visualization" task & update REST API

### ISSUE THREAD

**Issue by jlegrand62** [romi/plantdb#37]
Running "Visualization" task to access a scan and subsequent output is problematic:

- a scan cannot be viewed or accessed within the viewer after "data upload";
- "Visualization" task duplicates many data;
- REST API does not beneficiate from "Visualization" task data pre-processing (not simple enough);
- force to re-run "Visualization" task when updates instead of adding "version" check to REST API;

**Comment by hanappe** [comment]
Duplicate
